r"""Deploy guard — keep ``requirements.txt`` in sync with ``uv.lock``.

The committed ``requirements.txt`` is the dependency file Streamlit Community Cloud
installs from. It is a *generated* artifact (``uv export``), so it can silently drift
from ``uv.lock`` whenever a dependency changes. This guard regenerates the export and
compares the requirement specifiers, failing if the committed file is stale.

Regenerate with::

    uv export --frozen --no-dev --no-editable --no-hashes \
        --format requirements-txt -o requirements.txt
"""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

import pytest

# Resolve from this file (not the pytest CWD) so the guard is location-robust.
_REPO_ROOT = Path(__file__).resolve().parents[2]
_REQUIREMENTS = _REPO_ROOT / "requirements.txt"

# The exact flags the committed file was generated with; the comparison must use the
# same flags or it would report spurious drift. ``--frozen`` reads the existing lock
# without mutating it (no re-resolve side effect during the test run).
_EXPORT_CMD = [
    "uv",
    "export",
    "--frozen",
    "--no-dev",
    "--no-editable",
    "--no-hashes",
    "--format",
    "requirements-txt",
]


def _dependency_lines(text: str) -> list[str]:
    """Return the requirement specifiers only, in order — dropping blank lines and every
    comment (uv's autogenerated header *and* the indented ``# via`` annotations), so a
    harmless header/comment change never trips the guard while a real dep change does."""
    lines: list[str] = []
    for raw in text.splitlines():
        stripped = raw.strip()
        if not stripped or stripped.startswith("#"):
            continue
        lines.append(stripped)
    return lines


def test_requirements_file_exists_and_installs_project() -> None:
    assert _REQUIREMENTS.is_file(), "requirements.txt is missing — generate the deploy artifact"
    lines = _dependency_lines(_REQUIREMENTS.read_text(encoding="utf-8"))
    # The bare ``.`` installs the project itself; it is the most robust way to ensure the
    # sibling top-level packages (core, analytics, ui, visualization, …) are importable on
    # the deploy target. Guard it explicitly so it cannot be dropped silently.
    assert "." in lines, "requirements.txt must install the project ('.') so imports resolve"


@pytest.mark.skipif(shutil.which("uv") is None, reason="uv is not on PATH")
def test_requirements_in_sync_with_lockfile() -> None:
    proc = subprocess.run(
        _EXPORT_CMD,
        cwd=_REPO_ROOT,
        capture_output=True,
        text=True,
        check=True,
    )
    expected = _dependency_lines(proc.stdout)
    committed = _dependency_lines(_REQUIREMENTS.read_text(encoding="utf-8"))
    assert committed == expected, (
        "requirements.txt is out of sync with uv.lock. Regenerate with:\n"
        "    uv export --frozen --no-dev --no-editable --no-hashes "
        "--format requirements-txt -o requirements.txt"
    )
